### ISSUE TITLE
VCV Rack keep asking to update yours modules

### ISSUE THREAD

**Issue by caecos** [jatinchowdhury18/ChowDSP-VCV#10]
Check you json files since there is problem in the updating of your modules...

**Comment by egwspiti** [comment]
There's also the following entry in the log :
```[0.100 warn src/plugin.cpp:158] Could not load plugin C:\Users\user1\DOCUME~1/Rack/plugins-v1/ChowDSP: Failed to load library C:\Users\user1\DOCUME~1/Rack/plugins-v1/ChowDSP/plugin.dll: code 127```

**Comment by jatinchowdhury18** [comment]
Thank for reporting this! I'm currently working with the Rack Library maintainers to figure out what's going on. For more information see [here](https://github.com/VCVRack/library/issues/658#issuecomment-702989257).

**Comment by jatinchowdhury18** [comment]
Hi all,

Version 1.3.1 was made available on the VCV Library yesterday. If one of you could confirm if this issue has been resolved, that would be wonderful!

Thanks,
Jatin

**Comment by caecos** [comment]
Resolved !(Windows 10 Pro)

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : jatinchowdhury18<mailto:notifications@github.com>
Envoyé le :vendredi 9 octobre 2020 10:49
À : jatinchowdhury18/ChowDSP-VCV<mailto:ChowDSP-VCV@noreply.github.com>
Cc : caecos<mailto:caecos@hotmail.ca>; Author<mailto:author@noreply.github.com>
Objet :Re: [jatinchowdhury18/ChowDSP-VCV] VCV Rack keep asking to update yours modules (#10)


Hi all,

Version 1.3.1 was made available on the VCV Library yesterday. If one of you could confirm if this issue has been resolved, that would be wonderful!

Thanks,
Jatin

**Comment by jatinchowdhury18** [comment]
Wonderful, thank you!
