### ISSUE TITLE
LV2 ports?

### ISSUE THREAD

**Issue by mxmilkiib** [jatinchowdhury18/ChowDSP-VCV#11]
As LV2 supports [CV](https://linuxmusicians.com/viewtopic.php?f=1&t=20701) ports ([example project](https://github.com/mxmilkiib/carla-lv2-jack-nsm)), might you at some point be up for porting these for use in LV2 hosts?

**Comment by jatinchowdhury18** [comment]
Thanks for sharing the example project... it's definitely an interesting idea! I don't have any plans to port these modules to LV2 at the moment, but I'll keep the idea in mind for the future!

**Comment by mxmilkiib** [comment]
This will be possible using https://github.com/DISTRHO/Cardinal

There's lots of info on https://github.com/DISTRHO/Cardinal/issues/1 with chat in #kxstudio on libera.chat.

**Comment by mxmilkiib** [comment]
And they're in, thanks @falkTX! https://github.com/DISTRHO/Cardinal/discussions/63#discussioncomment-1749071

I'm gonna stick with Cardinal over VCV Rack, partly given the native JACK and LV2 CV pretty functionality.
