### ISSUE TITLE
v2: References to custom fonts stored across frames

### ISSUE THREAD

**Issue by cschol** [jatinchowdhury18/ChowDSP-VCV#23]
Your plugin stores references to custom fonts across frames. This leads to crashes in the VST when reloading a project.

For example (but there might be others):
```
WarpWidget(Warp* module) {
[...]
 modeLabel->font = APP->window->loadFont(asset::plugin(pluginInstance, "res/fonts/RobotoCondensed-Bold.ttf"));
[...]
```

Please see the following link on how to resolve this issue and re-submit to the Library:
https://vcvrack.com/manual/Migrate2#2-1-Don-t-store-Font-and-Image-references-across-multiple-frames

**Comment by jatinchowdhury18** [comment]
Thanks for catching this. I could only find one call to `loadFont()` or `loadImage()` in the codebase, which is now fixed with [this commit](https://github.com/jatinchowdhury18/ChowDSP-VCV/commit/3111fa75e5c73394309f111a2647c2c94397000a). I'm assuming the same issue does not apply to `loadSVG()`?

**Comment by cschol** [comment]
This does not affect `loadSVG()` (it is in memory, not GL context).

**Comment by jatinchowdhury18** [comment]
Great, thanks!
