### ISSUE TITLE
Artwork license question

### ISSUE THREAD

**Issue by falkTX** [jatinchowdhury18/ChowDSP-VCV#26]
Just a quick question, as I don't see it mentioned anywhere.
Your project is licensed under GPL-3.0-or-later, but does that include the graphics too? Or are those supposed to be in a different license?

The readme briefly mentions "Module design assisted by Margus Mets" but nothing else regarding licensing of the panels and artwork.

Thanks!

**Comment by jatinchowdhury18** [comment]
Yes, the module graphics are licensed under the same license as the code.

Thanks,
Jatin

**Comment by falkTX** [comment]
Do you mind clarifying it on the readme?

Something like:

> ChowDSP VCV Modules (both artwork and code) are licensed under the GPLv3 license. Enjoy!

Thanks again!

**Comment by jatinchowdhury18** [comment]
Done! And thank you :)
