### ISSUE TITLE
Module: Credits

### ISSUE THREAD

**Issue by Eurikon** [jatinchowdhury18/ChowDSP-VCV#7]
Hi Jatin,
do you have a link to the nightly that includes module: Credits?

I tried to build it from source, but both make -j4 & make install , didn't work for me.
Weird, cause earlier i could build it with make -j4

**Comment by jatinchowdhury18** [comment]
Hi Eurikon,

[This release](https://github.com/jatinchowdhury18/ChowDSP-VCV/releases/tag/AzureCI) contains the most up-to-date builds (for some reason the date doesn't update unless I delete the existing Azure release, and I haven't yet figured out how to automate that).

Curious why the plugin wouldn't build on your system... any information about your build setup and compiler logs would be useful.

Thanks so much!
Jatin

**Comment by Eurikon** [comment]
Just checked it now, excellent :D exactly what i needed hehe :) 

I will get back to you on the build-setup.

**Comment by Eurikon** [comment]
Hi Jatin, sorry for taking this long.
Thanks for adding that URL stamping option in the 1.3 version!

My build environment is Windows 10 pro / RackSDK 1.1.6 / MS2 MinGW
Before you switched to Azure, i was able to clone into the repo, and build with make -j4.

Now neither make or install works for me on your repo clone.

**Comment by jatinchowdhury18** [comment]
Hi Eurikon,

No worries! That's odd, I'm using the exact same build system for most of the development... Would you be able to share the console output from when you try to run `make`? Thanks!

**Comment by Eurikon** [comment]
Ok, it gets weirder.

Done exact the same as couple days ago, namely:  
clear out current directory of CHOW
clone the git
make -j4 (worked)
make dist (worked)

So, no idea what went wrong between couple of days ago and now. 
But now it works again!

All good :)

**Comment by jatinchowdhury18** [comment]
Whoa, very strange... my best guess is that something got corrupted, or out-of-sync in the hidden `.git` folder that manages the local copy of the repo. Either way, glad it's working now!

Thanks,
Jatin
